version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Adjust port if needed
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
